Add update tags reusable workflow
Ubix/github-actions-workflows pull request #1
Opened 2022-12-06 14:28 UTC by nelscata

Adding a workflow that will update the image tag in the values yaml file to allow ArgoCD syncing the new version of the app that is being updated

2022-12-06 14:32 UTC, jfmrm requested changes

2022-12-06 14:32 UTC, jfmrm commented on .github/workflows/cd-update-tag.yml
> +        # change tag with yq
we need here to add the yq command that edits the image tag. Example:
```
yq -i ".global.image.tag = \"$tag\"" <file-path>
```

2022-12-07 12:25 UTC, nelscata commented on .github/workflows/cd-update-tag.yml
> +        # change tag with yq
done, added the missing command, in addition an input var to get the path of the values file was added

2022-12-08 12:43 UTC, jfmrm approved these changes

2022-12-08 12:43 UTC, jfmrm commented on .github/workflows/cd-update-tag.yml
> +        required: false
this should be required.

2022-12-08 13:00 UTC, nelscata commented on .github/workflows/cd-update-tag.yml
> +        required: false
updated it

2022-12-08 13:47 UTC, merged